import { isUndecided } from "@shared/jev.ts"
import type { JevAnswer } from "@shared/jev.ts"

import type { PolicyLine } from "@/components/jev/PolicyTrace"
import { percent } from "@/lib/format"

/**
 * Below this, nobody gets auto-routed: the queue is a guess, so a human picks.
 */
export const ROUTABLE_CONFIDENCE = 0.6

/**
 * Billing needs more.
 *
 * A single global cutoff is the common mistake. Misrouting to `technical` costs
 * one queue hop; misrouting to `billing` puts the ticket in front of a team who
 * can issue a refund. The branches differ in blast radius, so they differ in
 * the confidence they demand.
 */
export const BILLING_CONFIDENCE = 0.85

/** A noul above this is treated as "yes" for escalation purposes. */
export const LIKELY = 0.7

/** Halfway between "inconvenience" and "active loss" on the 0–2 rubric. */
export const IMPACT_THRESHOLD = 1.5

export interface Decision {
  queue: string
  /** True when a person must look before anything is routed. */
  human: boolean
  notes: string[]
}

export interface Routed {
  decision: Decision
  /**
   * The policy as source, with the branches that fired on this input marked.
   *
   * Generated by the same function that decides, so the trace cannot drift out
   * of step with the logic it claims to describe.
   */
  trace: PolicyLine[]
}

type Answers = Record<string, JevAnswer>

/**
 * Turn seven answers into a queue.
 *
 * Escalation is two separate conditions rather than one weighted score:
 * a churn threat alone is enough, and so is sustained business impact on an
 * urgent ticket. Averaging them into a single number would let a serious signal
 * be diluted by the mild ones sitting beside it, which is exactly the case that
 * matters.
 */
export function route(answers: Answers): Routed {
  const department = answers.department
  const frustration = answers.frustration
  const impact = answers.business_impact
  const urgent = answers.is_urgent
  const churn = answers.threatens_churn
  const refund = answers.refund_requested
  const repeat = answers.is_repeat_contact

  if (department?.type !== "choice") {
    throw new Error("triage: `department` must be a choice answer")
  }
  if (impact?.type !== "score") {
    throw new Error("triage: `business_impact` must be a score answer")
  }

  const notes: string[] = []
  const trace: PolicyLine[] = []
  const line = (code: string, fired?: boolean, note?: string) =>
    trace.push({ code, fired, note })

  // --- annotations, which never gate anything on their own -----------------
  if (refund?.type === "noul" && refund.noul > LIKELY) notes.push("refund requested")
  if (repeat?.type === "noul" && repeat.noul > LIKELY) notes.push("repeat contact")
  if (frustration?.type === "score" && !isUndecided(frustration)) {
    if (frustration.score >= 1.5) notes.push("angry")
    else if (frustration.score >= 0.75) notes.push("annoyed")
  }

  // --- escalation ----------------------------------------------------------
  line("const LIKELY = 0.70")
  line(`const IMPACT_THRESHOLD = ${IMPACT_THRESHOLD}`)
  line("")

  const churnThreat = churn?.type === "noul" && churn.noul > LIKELY
  line(
    "if (churn > LIKELY)",
    churnThreat,
    churn?.type === "noul" ? `churn ${churn.noul.toFixed(2)}` : undefined,
  )
  if (churnThreat) {
    line("  return { queue: 'retention', human: true }", true)
    return {
      decision: {
        queue: "retention",
        human: true,
        notes: [...notes, "churn threat"],
      },
      trace,
    }
  }

  // --- confidence gates ----------------------------------------------------
  line("")
  line(`const ROUTABLE_CONFIDENCE = ${ROUTABLE_CONFIDENCE}`)
  line(`const BILLING_CONFIDENCE  = ${BILLING_CONFIDENCE}  // can move money`)
  line("")

  const flat = isUndecided(department)
  line(
    "if (isUndecided(department))",
    flat,
    flat ? "flat distribution" : undefined,
  )
  if (flat) {
    line("  return { queue: 'human-review', human: true }", true)
    return {
      decision: {
        queue: "human-review",
        human: true,
        notes: [...notes, "Jev could not tell — flat distribution"],
      },
      trace,
    }
  }

  const belowFloor = department.confidence < ROUTABLE_CONFIDENCE
  line(
    "if (department.confidence < ROUTABLE_CONFIDENCE)",
    belowFloor,
    belowFloor ? percent(department.confidence, 0) : undefined,
  )
  if (belowFloor) {
    line("  return { queue: 'human-review', human: true }", true)
    return {
      decision: {
        queue: "human-review",
        human: true,
        notes: [
          ...notes,
          `department confidence ${percent(department.confidence, 0)} below ${percent(ROUTABLE_CONFIDENCE, 0)}`,
        ],
      },
      trace,
    }
  }

  const billingUnderGate =
    department.choice === "billing" && department.confidence < BILLING_CONFIDENCE
  line(
    "if (department.choice === 'billing' && confidence < BILLING_CONFIDENCE)",
    billingUnderGate,
    billingUnderGate ? percent(department.confidence, 0) : undefined,
  )
  if (billingUnderGate) {
    line("  return { queue: 'human-review', human: true }", true)
    return {
      decision: {
        queue: "human-review",
        human: true,
        notes: [
          ...notes,
          `billing needs ${percent(BILLING_CONFIDENCE, 0)} to auto-route, got ${percent(department.confidence, 0)}`,
        ],
      },
      trace,
    }
  }

  // --- priority ------------------------------------------------------------
  line("")
  const isUrgent = urgent?.type === "noul" && urgent.noul > LIKELY
  const impacted = !isUndecided(impact) && impact.score >= IMPACT_THRESHOLD
  const priority = isUrgent && impacted
  line(
    "if (urgent > LIKELY && impact >= IMPACT_THRESHOLD)",
    priority,
    priority ? `impact ${impact.score.toFixed(2)}` : undefined,
  )
  if (priority) {
    line("  return { queue: `${department}/priority` }", true)
    return {
      decision: {
        queue: `${department.choice}/priority`,
        human: false,
        notes: [...notes, "urgent and losing money"],
      },
      trace,
    }
  }

  line("return { queue: `${department}/standard` }", true)
  return {
    decision: { queue: `${department.choice}/standard`, human: false, notes },
    trace,
  }
}
